site_name: Copilot Studio Utbildning
theme:
  name: material
  language: sv
  features:
    - content.code.copy
nav:
  - Hem: index.md
  - 0. Förberedelser: 00-setup.md
  - 1. Förbered SharePoint: 01-prepare-sharepoint.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences