site_name: Copilot Studio Utbildning
theme:
  name: material
  language: sv
  features:
    - content.code.copy
nav:
  - Hem: index.md
  - 0. Förberedelser: 00-setup.md
  - 1. Förbered SharePoint: 01-prepare-sharepoint.md
  - 2. Hitta rätt i Copilot Studio: 02-tour-interface.md
  - 3. Skapa Solution: 03-create-solution.md
  - 4. Skapa Agent: 04-create-agent.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html